name: "Install Wazuh build dependencies"
description: "This action installs all the requirements to test and build Wazuh agent/server in Ubuntu Linux"
inputs:
   target:
     required: true
     description: "Wazuh target to decide if install or not custom dependencies"
runs:
  using: "composite"
  steps:
    - name: Install tools and libraries
      shell: bash
      run: sudo apt install cppcheck astyle valgrind lcov clang-tools libcmocka-dev -y
    - name: Install mingw
      if: ${{ inputs.target }} == 'winagent'
      shell: bash
      run: sudo apt install gcc-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 nsis -y
    - name: Install wine
      if: ${{ inputs.target }} == 'winagent'
      shell: bash
      run: |
        sudo dpkg --add-architecture i386 && sudo apt update
        sudo apt install -y --install-recommends wine-stable
    - name: Install CMocka by sources for winagent
      if: ${{ inputs.target }} == 'winagent'
      shell: bash
      run: |
        cd /tmp
        curl -L https://git.cryptomilk.org/projects/cmocka.git/snapshot/stable-1.1.tar.gz | \
        tar zvx -C /tmp/ && \
        sed -i "s|ON|OFF|g" /tmp/stable-1.1/DefineOptions.cmake && \
        mkdir /tmp/stable-1.1/build && \
        cd /tmp/stable-1.1/build && \
        cmake -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc -DCMAKE_C_LINK_EXECUTABLE=i686-w64-mingw32-ld -DCMAKE_INSTALL_PREFIX=/usr/i686-w64-mingw32/ -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_BUILD_TYPE=Release .. && \
        make && \
        sudo make install && \
        cd $GITHUB_WORKSPACE
