name: "Vulnerability scanner dependencies"
description: "Download and compiles the dependencies for the vulnerability scanner modules"

runs:
  using: "composite"
  steps:    
      - name: External deps
        run: |
          cd src
          make deps TARGET=server -j2
          make build_gtest TARGET=server -j2
          make libwazuhext.so TARGET=server -j2
        shell: bash

      - name: http-request
        run: |
          cd src
          SRC_FOLDER=$(pwd)

          cd shared_modules/http-request
          mkdir -p build && cd build
          cmake .. -DCMAKE_PROJECT_NAME=http-request -DSRC_FOLDER=${SRC_FOLDER} && make -j2
        shell: bash
