name: "Upload artifact"
description: "This action is a wrapper of actions/upload-artifact@vX to centralize version management"
inputs:
   name:
     required: true
     description: "Name of the artifact"
   path:
     required: true
     description: "Folder with files to upload"
runs:
  using: "composite"
  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
