name: "Doxygen documentation generartion"
description: "Generates the documentation for a given module"

inputs:
  path:
    required: true
    description: "Path to the module we want to generate documentation for"
    default: src/
  doxygen_config:
    required: true
    description: "Path to the doxygen configuration file"
    default: src/Doxyfile

runs:
  using: "composite"
  steps:    
      # Dependencies for testing:
      # - doxygen 
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen
          version: 1.0

      - name: Generate documentation
        shell: bash
        run: |

          # Generate the doxygen configuration file
          CONFIG_FILE=${{ inputs.path }}/doxygen_config.cfg
          {
              cat ${{ inputs.doxygen_config }}
              echo "OUTPUT_DIRECTORY = ${{ inputs.path }}/doc"
              echo "INPUT = ${{ inputs.path }}"
          } > ${CONFIG_FILE}

          # Generate the documentation
          ERRORS_FILE=${{ inputs.path }}/doxygen_errors.txt
          doxygen -s ${CONFIG_FILE} 2> ${ERRORS_FILE}

          # Check if there are errors
          if [ -s "${ERRORS_FILE}" ]; then
            echo "Documentation errors found"
            exit 1
          else
            echo "Documentation generated successfully"
          fi

      # Upload errors as an artifact, when failed
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Doxygen errors
          path: ${{ inputs.path }}/doxygen_errors.txt
          retention-days: 1

      # Upload the documentation as an artifact, when successful
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: Doxygen documentation
          path: ${{ inputs.path }}/doc
          retention-days: 1
