name: "Doxygen documentation generartion"
description: "Generates the documentation for a given module"

inputs:
  path:
    required: true
    description: "Path to the module we want to generate documentation for"
    default: src/
  doxygen-config:
    required: true
    description: "Path to the doxygen configuration file"
    default: Doxyfile

runs:
  using: "composite"
  steps:    
      # Dependencies for testing:
      # - doxygen 
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen
          version: 1.0

      - name: Generate documentation
        run: |

          
        shell: bash
