name: decoder/windows-security/0

sources:
  - decoder/windows-event-decoder/0

metadata:
  description: Decoder for Windows Security events
  module: Windows Security
  title: Decoder for Windows Security and Windows Eventlog auditing
  compatibility: >
    This decoder has been tested on Wazuh version 4.3
  author:
    name: Wazuh, Inc.
    date: 2023/01/23
  references:
    - https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/security-auditing-overview
  versions: [Vista, "7", "8", "10", "11", Server 2012, Server 2016, Server 2019, Server 2022]

check: ~windows.Event.System.Channel.#text==Security AND (event.provider==Microsoft-Windows-Security-Auditing OR event.provider==Microsoft-Windows-Eventlog)


normalize:
 - map:
    - wazuh.decoders: +array_append/windows-security
    - event.dataset: security

    # Set categorization fields
    - event: +kvdb_get_merge/win_security_categories/$event.id

    # Set Service Type and Name
    # Service related fields
    - service.name: $~windows.Event.EventData.ServiceName

    - user.target.name: $~windows.Event.EventData.OldTargetUserName
    - user.changes.name: $~windows.Event.EventData.NewTargetUserName
    - related.user: +array_append/$~windows.Event.EventData.NewTargetUserName
    - related.user: +array_append/$~windows.Event.EventData.OldTargetUserName

    # map helper arrays
    - ~temp.id_target_user_array: ["4624","4625","4634","4647","4648","4768","4769","4770","4771","4776","4964"]
    - ~temp.id_memberName_array: ["4727", "4728", "4729", "4730", "4731", "4732", "4733", "4734", "4735",
                              "4737", "4744", "4745", "4746", "4747", "4748", "4749", "4750", "4751",
                              "4752", "4753", "4754", "4755", "4756", "4757", "4758", "4759", "4760",
                              "4761", "4762", "4763", "4764", "4799"]
    - ~temp.id_copy_subject_user_array: ["4657", "4670", "4672", "4673", "4674", "4688", "4689", "4697",
              "4698", "4699", "4700", "4701", "4702", "4706", "4707", "4713",
              "4716", "4717", "4718", "4719", "4720", "4722", "4723", "4724",
              "4725", "4726", "4727", "4728", "4729", "4730", "4731", "4732",
              "4733", "4734", "4735", "4737", "4738", "4739", "4740", "4741",
              "4742", "4743", "4744", "4745", "4746", "4747", "4748", "4749",
              "4750", "4751", "4752", "4753", "4754", "4755", "4756", "4757",
              "4758", "4759", "4760", "4761", "4762", "4763", "4764", "4767",
              "4781", "4798", "4799", "4817", "4904", "4905", "4907", "4912",
              "4648"]
    - ~temp.id_copy_target_user_array: ["4670", "4720", "4722", "4723", "4724", "4725",
              "4726", "4738", "4740", "4767", "4798", "4817", "4907"]
    - ~temp.id_rename_common_auth_fields: ["1100", "1102", "1104", "1105", "1108", "4624", "4648", "4625",
              "4670", "4673", "4674", "4689", "4697", "4719", "4720", "4722",
              "4723", "4724", "4725", "4726", "4727", "4728", "4729", "4730",
              "4731", "4732", "4733", "4734", "4735", "4737", "4738", "4740",
              "4741", "4742", "4743", "4744", "4745", "4746", "4747", "4748",
              "4749", "4750", "4751", "4752", "4753", "4754", "4755", "4756",
              "4757", "4758", "4759", "4760", "4761", "4762", "4763", "4764",
              "4767", "4768", "4769", "4770", "4771", "4798", "4799", "4817",
              "4904", "4905", "4907", "4912"]
    - ~temp.id_related_user:  ["4688", "4720", "4722", "4723", "4724", "4725", "4726", "4738",
         "4740", "4767", "4798"]


    # Add Session Events
 - check: event.code=="4778" OR event.code=="4779"
   map:
        # AccountName to user.name and related.user
        - user.name: $~windows.Event.EventData.AccountName
        - related.user: +array_append/$~windows.Event.EventData.AccountName
        # AccountDomain to user.domain
        - user.domain: $~windows.Event.EventData.AccountDomain
        # ClientAddress to source.ip and related.ip
        - source.ip: $~windows.Event.EventData.ClientAddress
        - related.ip: +array_append/$~windows.Event.EventData.ClientAddress
        # ClientName to source.domain
        - source.domain: $~windows.Event.EventData.ClientName

    # Copy Target User
    # TargetUserSid to user.id or user.target.id
 - check: +not_exists/user.id AND +array_contains/~temp.id_target_user_array/$event.code
   map:
        - user.id: $~windows.Event.EventData.TargetUserSid
        - user.id: $~windows.Event.EventData.TargetSid

 - check: +exists/user.id AND +array_contains/~temp.id_target_user_array/$event.code
   map:
        - user.target.id: $~windows.Event.EventData.TargetUserSid
        - user.target.id: $~windows.Event.EventData.TargetSid

 # TargetUserName to related.user and user.name or user.target.name
 - check: +not_exists/user.name AND +array_contains/~temp.id_target_user_array/$event.code
   map:
        - user.name: $~windows.Event.EventData.TargetUserName
 - check: +exists/user.name AND +array_contains/~temp.id_target_user_array/$event.code
   map:
        - user.target.name: $~windows.Event.EventData.TargetUserName

 - check: +string_not_equal/~windows.Event.EventData.TargetUserName/- AND +array_contains/~temp.id_target_user_array/$event.code
   map:
        - related.user: +array_append/$~windows.Event.EventData.TargetUserName 

    # TargetUserDomain to user.domain or user.target.domain
 - check: +not_exists/user.domain AND +array_contains/~temp.id_target_user_array/$event.code
   map:
        - user.domain: $~windows.Event.EventData.TargetDomainName
 - check: +exists/user.domain AND +array_contains/~temp.id_target_user_array/$event.code
   map:
        - user.target.domain: $~windows.Event.EventData.TargetDomainName

    # Copy MemberName to User and User to Group
 - check:
        - ~temp.id_memberName_array: +array_contains/event.code
   map:
        - ~temp.split_memberName: +split/$~windows.Event.EventData.MemberName/,
        - ~temp.split_memberName.0: '+replace/CN=/'
        - user.target.name: $~temp.split_memberName.0
        - related.user: +array_append/$~temp.split_memberName.0
        - group.id: $~windows.Event.EventData.TargetUserSid
        - group.id: $~windows.Event.EventData.TargetSid
        - group.name: $~windows.Event.EventData.TargetUserName
        - ~windows.Event.EventData.TargetDomainName: '+replace/DC=/'
        - group.domain: $~windows.Event.EventData.TargetDomainName
        - user.target.group.id: $group.id
        - user.target.group.name: $group.name
        - user.target.group.domain: $group.domain
        - ~temp.split_memberName.3: '+replace/DC=/'
        - user.target.domain: $~temp.split_memberName.3

 # Copy Subject User from Event Data
 - check:
     - ~temp.id_copy_subject_user_array: +array_contains/$event.code
   map:
     - user.id: $~windows.Event.EventData.SubjectUserSid
     - user.name: $~windows.Event.EventData.SubjectUserName
     - related.user: +array_append/$~windows.Event.EventData.SubjectUserName
     - user.domain: $~windows.Event.EventData.SubjectDomainName

 # Copy Target User to Target
 - check:
    - ~temp.id_copy_target_user_array: +array_contains/$event.code
   map:
     - user.target.id: $~windows.Event.EventData.TargetSid
     - ~temp.name_part: +split/$~windows.Event.EventData.TargetUserName/@
     - user.target.name: $~temp.name_part.0
     - related.user: +array_append/event.user.target.name
     - user.target.domain: $~windows.Event.EventData.TargetDomainName

# Copy Target User to Effective
 - check: event.code=="4648" OR event.code=="4688"
   map:
     - user.effective.id: $~windows.Event.EventData.TargetUserSid


 - check: +string_not_equal/~windows.Event.EventData.TargetUserName/- AND  (event.code=="4648" OR event.code=="4688")
   map:
     - ~temp.name_part: +split/$~windows.Event.EventData.TargetUserName/@
     - user.effective.name: $~temp.name_part.0
     - related.user: +array_append/event.user.effective.name


 - check: +string_not_equal/~windows.Event.EventData.TargetDomainName/- AND  (event.code=="4648" OR event.code=="4688")
   map:
     - user.effective.domain: $~windows.Event.EventData.TargetDomainName

# Copy Subject User from user_data
 - check: event.code=="1102"
   map:
     - user.id: $~windows.Event.UserData.LogFileCleared.SubjectUserSid.#text
     - user.name: $~windows.Event.UserData.LogFileCleared.SubjectUserName.#text
     - related.user: +array_append/$~windows.Event.UserData.LogFileCleared.SubjectUserName.#text
     - user.domain: $~windows.Event.UserData.LogFileCleared.SubjectDomainName.#text


# Rename Common Auth Fields
 - check:
     - ~temp.id_rename_common_auth_fields: +array_contains/$event.code
   map:
     - process.pid: +hex_to_number/$~windows.Event.EventData.ProcessId
     - process.executable: $~windows.Event.EventData.ProcessName
     - ~temp.file_data: +parse_file/$~windows.Event.EventData.ProcessName
     - process.name: $~temp.file_data.name

 - check: +array_contains/~temp.id_rename_common_auth_fields/$event.code AND +string_not_equal/~windows.Event.EventData.IpAddress/-
   map:  
     - source.ip: $~windows.Event.EventData.IpAddress
     - source.port: $~windows.Event.EventData.IpPort
     - source.domain: $~windows.Event.EventData.WorkstationName
     - related.ip: +array_append/$~windows.Event.EventData.ClientAddress

# Process Event 4688
 - check: event.code=="4688"
   map:
     - process.args: '+split/$~windows.Event.EventData.CommandLine/ '
     - process.pid: +hex_to_number/$~windows.Event.EventData.NewProcessId
     - process.executable: $~windows.Event.EventData.NewProcessName
     - ~temp.file_data: +parse_file/$~windows.Event.EventData.NewProcessName
     - process.name: $~temp.file_data.name
     - process.parent.pid: +hex_to_number/$~windows.Event.EventData.ProcessId
     - process.parent.executable:  $~windows.Event.EventData.ParentProcessName
     - ~temp.file_data: +parse_file/$~windows.Event.EventData.ParentProcessName
     - process.parent.name: $~temp.file_data.name
     - process.command_line: $~windows.Event.EventData.CommandLine

 - check: event.code=="4624" OR event.code=="4648"
   map:
     - related.user: $~windows.Event.EventData.SubjectUserName

 - check:
      - ~temp.id_related_user: +array_contains/$event.code
   map:
      - related.user: +array_append/$~windows.Event.EventData.TargetUserName

 - map:
     - related.ip: +array_append/$source.ip

# Set Service Type
 - check:
    - ~windows.Event.EventData.ServiceType: "0x1"
   map:
    - service.type: "Kernel Driver"

 - check:
    - ~windows.Event.EventData.ServiceType: "0x2"
   map:
    - service.type: "File System Driver"

 - check:
    - ~windows.Event.EventData.ServiceType: "0x8"
   map:
    - service.type: "Recognizer Driver"

 - check:
    - ~windows.Event.EventData.ServiceType: "0x10"
   map:
    - service.type: "Win32 Own Process"

 - check:
    - ~windows.Event.EventData.ServiceType: "0x20"
   map:
    - service.type: "Win32 Share Process"

 - check:
    - ~windows.Event.EventData.ServiceType: "0x110"
   map:
    - service.type: "Interactive Own Process"

 - check:
    - ~windows.Event.EventData.ServiceType: "0x120"
   map:
    - service.type: "Interactive Share Process"

# Cleanup
 - map:
   - ~temp: +delete
   - ~windows: +delete
