name: decoder/windows-security/0

metadata:
  description: Decoder for Windows Security events
  module: Windows Security
  title: Decoder for Windows Security and Windows Eventlog auditing
  compatibility: >
    This decoder has been tested on Wazuh version 4.3
  author:
    name: Wazuh, Inc.
    date: 2023/01/23
  references:
    - https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/security-auditing-overview
  versions: [Vista, "7", "8", "10", "11", Server 2012, Server 2016, Server 2019, Server 2022]

definitions:
  MAP_KerberosEncryptionType:
    "0x1": DES-CBC-CRC
    "0x3": DES-CBC-MD5
    "0x11": AES128-CTS-HMAC-SHA1-96
    "0x12": AES256-CTS-HMAC-SHA1-96
    "0x17": RC4-HMAC
    "0x18": RC4-HMAC-EXP
    "0xffffffff": FAIL

  MAP_TrustType:
    1: TRUST_TYPE_DOWNLEVEL
    2: TRUST_TYPE_UPLEVEL
    3: TRUST_TYPE_MIT
    4: TRUST_TYPE_DCE

  MAP_TrustDirection:
    0: TRUST_DIRECTION_DISABLED
    1: TRUST_DIRECTION_INBOUND
    2: TRUST_DIRECTION_OUTBOUND
    3: TRUST_DIRECTION_BIDIRECTIONAL

  MAP_LogonType:
    2 : Interactive
    3 : Network
    4 : Batch
    5 : Service
    7 : Unlock
    8 : NetworkCleartext
    9 : NewCredentials
    10 : RemoteInteractive
    11 : CachedInteractive

  MAP_ServiceType:
    "0x10": "Win32 Own Process"
    "0x20": "Win32 Share Process"
    "0x110": "Interactive Own Process"
    "0x120": "Interactive Share Process"

  # Array column form
  ~MAP_IdTargetUserArray:
    - "4624":
    - "4625":
    - "4634":
    - "4647":
    - "4648":
    - "4768":
    - "4769":
    - "4770":
    - "4771":
    - "4776":
    - "4964":

  # Array List form
  ~MAP_IdMemberName: ["4727", "4728", "4729", "4730", "4731", "4732", "4733", "4734", "4735", "4737", "4744",
    "4745", "4746", "4747", "4748", "4749", "4750", "4751","4752", "4753", "4754", "4755", "4756", "4757", "4758", "4759",
    "4760","4761", "4762", "4763", "4764", "4799"]

  # Object Form
  ~MAP_IdCopyTargetUserArray:
    "4670":
    "4720":
    "4722":
    "4723":
    "4724":
    "4725":
    "4726":
    "4738":
    "4740":
    "4767":
    "4798":
    "4817":
    "4907":

  ~MAP_IdRenameCommonAuthFields: ["1100","1102","1104","1105","1108","4624","4648","4625","4670","4673","4674","4689",
    "4697","4719","4720","4722","4723","4724","4725","4726","4727","4728","4729","4730","4731","4732","4733","4734",
    "4735","4737","4738","4740","4741","4742","4743","4744","4745","4746","4747","4748","4749","4750","4751","4752",
    "4753","4754","4755","4756","4757","4758","4759","4760","4761","4762","4763","4764","4767","4768","4769","4770",
    "4771","4798","4799","4817","4904","4905","4907","4912"]

  ~temp.id_related_user:  ["4688", "4720", "4722", "4723", "4724", "4725", "4726", "4738", "4740", "4767", "4798"]

sources:
  - decoder/windows-event-decoder/0

check: ~windows.System.Channel.#text==Security AND (event.provider==Microsoft-Windows-Security-Auditing OR event.provider==Microsoft-Windows-Eventlog)

normalize:
 - map:
    - wazuh.decoders: +array_append/windows-security
    - event.dataset: security

    # Categorization fields
    - event: +kvdb_get_merge/win_security_categories/$event.id

    # User Account Control
    # TODO: DoubleCheck Correct implementation needs bitwise operations - Opting to use raw value
    - ~winlog.NewUserAccountControl: $~windows.EventData.NewUacValue
    - ~winlog.UserAccountControl: +split/$~windows.EventData.UserAccountControl/%

    # Service Type and Name
    - service.name: $~windows.EventData.ServiceName

    # Set Trust Attributes
    # TODO DOUBLE CHECK: user.id or user.effective.id or client.user.id
    - user.id: $~windows.EventData.SubjectLogonId
    # TODO: can user.changes.roles fix in here?
    - ~winlog.User_PrivilegeList: '+split/$~windows.EventData.PrivilegeList/ '

    - user.target.name: $~windows.EventData.OldTargetUserName
    - user.changes.name: $~windows.EventData.NewTargetUserName
    - related.user: +array_append/$~windows.EventData.NewTargetUserName
    - related.user: +array_append/$~windows.EventData.OldTargetUserName

    # Failure reason for logon
 - check:
    - ~windows.EventData.FailureReason: +exists
   map:
    - event.action: logon failed
    - event.reason: +kvdb_get/failure_codes_descriptions/$~windows.EventData.FailureReason

  # Conditional Logon
 - check: event.code=="4625" OR event.code=="4776"
   map:
    - event.action: logon failed
    - event.reason: +kvdb_get/win_logon_status/$~windows.EventData.Status

    # Add Session Events
 - check: $event.code=="4778" OR $event.code=="4779"
   map:
    - user.name: $~windows.EventData.AccountName
    - related.user: +array_append/$~windows.EventData.AccountName
    - user.domain: $~windows.EventData.AccountDomain
    - source.ip: $~windows.EventData.ClientAddress
    - related.ip: +array_append/$~windows.EventData.ClientAddress
    - source.domain: $~windows.EventData.ClientName

    # TODO: double check LogonID
    - user.id: $~windows.EventData.LogonID

    # Copy Target User
    # TargetUserSid to user.id or user.target.id
 - check: +not_exists/$user.id AND +array_contains/$~MAP_IdTargetUserArray/$event.code
   map:
    - user.id: $~windows.EventData.TargetUserSid
    - user.id: $~windows.EventData.TargetSid

 - check: +exists/$user.id AND +array_contains/$~MAP_IdTargetUserArray/$event.code
   map:
    - user.target.id: $~windows.EventData.TargetUserSid
    - user.target.id: $~windows.EventData.TargetSid

 # TargetUserName to related.user and user.name or user.target.name
 - check: +not_exists/$user.name AND +array_contains/$~MAP_IdTargetUserArray/$event.code
   map:
    - user.name: $~windows.EventData.TargetUserName
 - check: +exists/$user.name AND +array_contains/$~MAP_IdTargetUserArray/$event.code
   map:
    - user.target.name: $~windows.EventData.TargetUserName

 - check: +string_not_equal/$~windows.EventData.TargetUserName/- AND +array_contains/$~MAP_IdTargetUserArray/$event.code
   map:
    - related.user: +array_append/$~windows.EventData.TargetUserName

    # TargetUserDomain to user.domain or user.target.domain
 - check: +not_exists/$user.domain AND +array_contains/$~MAP_IdTargetUserArray/$event.code
   map:
    - user.domain: $~windows.EventData.TargetDomainName
 - check: +exists/$user.domain AND +array_contains/$~MAP_IdTargetUserArray/$event.code
   map:
    - user.target.domain: $~windows.EventData.TargetDomainName


 - check:
    - ~MAP_IdMemberName: +array_contains/$event.code
   map:
    - ~temp.split_memberName: +split/$~windows.EventData.MemberName/,
    - ~temp.split_memberName.0: '+replace/CN=/'
    - user.target.name: $~temp.split_memberName.0
    - related.user: +array_append/$~temp.split_memberName.0
    - group.id: $~windows.EventData.TargetUserSid
    - user.target.id: $~windows.EventData.TargetSid
    - user.target.name: $~windows.EventData.TargetUserName
    - ~windows.EventData.TargetDomainName: '+replace/DC=/'
    - group.domain: $~windows.EventData.TargetDomainName
    - user.target.group.id: $group.id
    - user.target.group.name: $group.name
    - user.target.group.domain: $group.domain
    - ~temp.split_memberName.3: '+replace/DC=/'
    - user.target.domain: $~temp.split_memberName.3

 - check: event.code=="4741" OR event.code=="4742" OR event.code=="4743"
   map:
    - user.target.id: $~windows.EventData.TargetSid
    - user.target.name: $~windows.EventData.TargetUserName
    - user.target.domain: $~windows.EventData.TargetDomainName

 - check: event.code=="4634" OR event.code=="4647" OR event.code=="4964"
   map:
    - user.id: $~windows.EventData.TargetLogonId

 # Copy Target User
 - check: +match_key/~MAP_IdCopyTargetUserArray/$event.code
   map:
    - user.target.id: $~windows.EventData.TargetSid
    - ~temp.name_part: +split/$~windows.EventData.TargetUserName/@
    - user.target.name: $~temp.name_part.0
    - related.user: +array_append/event.user.target.name
    - user.target.domain: $~windows.EventData.TargetDomainName

# Copy Target User to Effective
 - check: $event.code=="4648" OR $event.code=="4688"
   map:
    - user.effective.id: $~windows.EventData.TargetUserSid


 - check: +string_not_equal/$~windows.EventData.TargetUserName/- AND  ($event.code=="4648" OR $event.code=="4688")
   map:
    - ~temp.name_part: +split/$~windows.EventData.TargetUserName/@
    - user.effective.name: $~temp.name_part.0
    - related.user: +array_append/event.user.effective.name


 - check: +string_not_equal/$~windows.EventData.TargetDomainName/- AND  ($event.code=="4648" OR $event.code=="4688")
   map:
    - user.effective.domain: $~windows.EventData.TargetDomainName

 # Copy Subject User
 - check: +kvdb_match/event.code/win_id_copy_subject_user
   map:
    - user.id: $~windows.EventData.SubjectUserSid
    - user.name: $~windows.EventData.SubjectUserName
    - related.user: +array_append/$~windows.EventData.SubjectUserName
    - user.domain: $~windows.EventData.SubjectDomainName

 - check: event.code=="1102"
   map:
    - user.id: $~windows.UserData.LogFileCleared.SubjectUserSid.#text
    - user.name: $~windows.UserData.LogFileCleared.SubjectUserName.#text
    - related.user: +array_append/$~windows.UserData.LogFileCleared.SubjectUserName.#text
    - user.domain: $~windows.UserData.LogFileCleared.SubjectDomainName.#text
    - event.action: Log clear

# Rename Common Auth
 - check: +array_contains/~MAP_IdRenameCommonAuthFields/$event.code
   map:
    - process.pid: +hex_to_number/$~windows.EventData.ProcessId
    - process.executable: $~windows.EventData.ProcessName
    - ~temp.file_data: +parse_file/$~windows.EventData.ProcessName
    - process.name: $~temp.file_data.name

 - check: +array_contains/~MAP_IdRenameCommonAuthFields/$event.code AND +string_not_equal/~windows.EventData.IpAddress/-
   map:
    - source.ip: $~windows.EventData.IpAddress
    - source.port: $~windows.EventData.IpPort
    - source.domain: $~windows.EventData.WorkstationName
    - related.ip: +array_append/$~windows.EventData.ClientAddress

 - check: $event.code=="4688"
   map:
    - process.args: '+split/$~windows.EventData.CommandLine/ '
    - process.pid: +hex_to_number/$~windows.EventData.NewProcessId
    - process.executable: $~windows.EventData.NewProcessName
    - ~temp.file_data: +parse_file/$~windows.EventData.NewProcessName
    - process.name: $~temp.file_data.name
    - process.parent.pid: +hex_to_number/$~windows.EventData.ProcessId
    - process.parent.executable:  $~windows.EventData.ParentProcessName
    - ~temp.file_data: +parse_file/$~windows.EventData.ParentProcessName
    - process.parent.name: $~temp.file_data.name
    - process.command_line: $~windows.EventData.CommandLine

 - check: event.code=="4624" OR event.code=="4648"
   map:
    - related.user: +array_append/$~windows.EventData.SubjectUserName

 - check: event.code=="1105"
   map:
    - event.action: Log automatic backup
    - ~winlog.UserDataBackupPath: $~windows.UserData.AutoBackup.BackupPath.#text
    - ~winlog.UserDataChannel: $~windows.UserData.AutoBackup.Channel.#text

 - check:
    - ~temp.id_related_user: +array_contains/$event.code
   map:
    - related.user: +array_append/$~windows.EventData.TargetUserName

 - map:
    - related.ip: +array_append/$source.ip
    - service.type: "Recognizer Driver"

 - check: event.code=="4670" OR event.code=="4817" OR event.code=="4907" OR event.code=="4808"
   map:
    - ~winlog.NewSecurityDescriptor: $~windows.EventData.NewSd
    - ~winlog.OldSecurityDescriptor: $~windows.EventData.OldSd
    - ~winlog.ObjectType: $~windows.EventData.ObjectType
    - ~winlog.ObjectServer: $~windows.EventData.ObjectServer
    - ~winlog.ObjectName: $~windows.EventData.ObjectName

# Cleanup
 - map:
    - service.type: +get_value/$MAP_ServiceType/$~windows.EventData.ServiceType
    # Set Kerberos Encryption Types
    - ~winlog.TicketEncryptionTypeDescription: +get_value/$MAP_KerberosEncryptionType/$~windows.EventData.TicketEncryptionType
    # Set Trust Direction
    - ~winlog.TrustDirection: +get_value/$MAP_TrustDirection/$~windows.EventData.TdoDirection
    # Set trust type
    - ~winlog.TrustType: +get_value/$MAP_TrustType/$~windows.EventData.TdoType
    # Set Logon Type
    - ~winlog.LogonType: +get_value/$MAP_LogonType/$~windows.EventData.LogonType

    #cleanup
    - ~temp: +delete
    - ~windows: +delete
