run-name: Package - Upload Docker images with ${{ inputs.tag }}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: |
          Tag name of the Docker image to be uploaded
          (Use developer to set branch name.
          Use auto to set src/VERSION content)
        required: false
        default: auto
  push:
    branches: 
      - '[0-9]+.[0-9]+.[0-9]+'
    paths:
      - 'packages/**'

jobs:
  Upload-package-building-images:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - uses: actions/checkout@v4

      - name: Get changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            pkg_deb_manager_builder_amd64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/debs/amd64/manager/**'
              - 'packages/debs/utils/**'
            pkg_rpm_manager_builder_amd64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/amd64/manager/**'
              - 'packages/rpms/utils/**'
            pkg_deb_agent_builder_amd64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/debs/amd64/agent/**'
              - 'packages/debs/utils/**'
            pkg_deb_agent_builder_i386:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/debs/i386/agent/**'
              - 'packages/debs/utils/**'
            pkg_rpm_agent_builder_amd64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/amd64/agent/**'
              - 'packages/rpms/utils/**'
            pkg_rpm_agent_builder_i386:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/i386/agent/**'
              - 'packages/rpms/utils/**'
            pkg_rpm_legacy_builder_amd64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/amd64/legacy/**'
              - 'packages/rpms/utils/**'      
            pkg_rpm_legacy_builder_i386:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/i386/legacy/**'
              - 'packages/rpms/utils/**'       
            compile_windows_agent:
              - 'packages/windows/**'

      - name: Set tag and WAZUH_WORKFLOWS_BRANCH
        run: |
          VERSION=$(sed 's/^v\([0-9]*\.[0-9]*\.[0-9]*\)/\1/' $GITHUB_WORKSPACE/src/VERSION)
          if [ "${{ inputs.tag }}" == "auto" ]; then echo "TAG=$VERSION" >> $GITHUB_ENV;
          elif [ "${{ inputs.tag }}" == "developer" ]; then echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV;
          else echo "TAG=${{ inputs.tag }}" >> $GITHUB_ENV; fi
          echo "WAZUH_WORKFLOWS_BRANCH=1-migrate-upload-packages-workflows" >> $GITHUB_ENV

      - name: Request pkg_deb_manager_builder_amd64 update 
        if: steps.changes.outputs.pkg_deb_manager_builder_amd64 == 'true'
        run: |
          gh workflow run packages-upload-manager-images.yml -r ${{ github.ref_name }} -f tag=${{ env.TAG }} -f system=deb -f source_reference=${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Request pkg_rpm_manager_builder_amd64 update
        if: steps.changes.outputs.pkg_rpm_manager_builder_amd64 == 'true'
        run: |
          gh workflow run packages-upload-manager-images.yml -r ${{ github.ref_name }} -f tag=${{ env.TAG }} -f system=rpm -f source_reference=${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Request pkg_deb_agent_builder_amd64 update
        if: steps.changes.outputs.pkg_deb_agent_builder_amd64 == 'true'
        run: | 
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \ 
            -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/wazuh/wazuh-agent-packages/actions/workflows/packages-upload-image-amd.yml/dispatches \  
            -d '{"ref": "${{ env.WAZUH_WORKFLOWS_BRANCH }}", \
            "inputs": {"container_name": "pkg_deb_agent_builder_amd64", \ 
                       "dockerfile_path": "packages/debs/amd64/agent", \
                       "tag": "${{ env.TAG }}", \  
                       "wazuh_wazuh_branch": "${{ github.ref_name }}"}}'

      - name: Request pkg_deb_agent_builder_i386 update
        if: steps.changes.outputs.pkg_deb_agent_builder_i386 == 'true'
        run: | 
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \ 
            -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/wazuh/wazuh-agent-packages/actions/workflows/packages-upload-image-amd.yml/dispatches \  
            -d '{"ref": "${{ env.WAZUH_WORKFLOWS_BRANCH }}", \
            "inputs": {"container_name": "pkg_deb_agent_builder_i386", \ 
                       "dockerfile_path": "packages/debs/i386/agent", \
                       "tag": "${{ env.TAG }}", \  
                       "wazuh_wazuh_branch": "${{ github.ref_name }}"}}'

      - name: Request pkg_rpm_agent_builder_amd64 update
        if: steps.changes.outputs.pkg_rpm_agent_builder_amd64 == 'true'
        run: | 
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \ 
            -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/wazuh/wazuh-agent-packages/actions/workflows/packages-upload-image-amd.yml/dispatches \  
            -d '{"ref": "${{ env.WAZUH_WORKFLOWS_BRANCH }}", \
            "inputs": {"container_name": "pkg_rpm_agent_builder_amd64", \ 
                       "dockerfile_path": "packages/rpms/amd64/agent", \
                       "tag": "${{ env.TAG }}", \  
                       "wazuh_wazuh_branch": "${{ github.ref_name }}"}}'

      - name: Request pkg_rpm_agent_builder_i386 update
        if: steps.changes.outputs.pkg_rpm_agent_builder_i386 == 'true'
        run: | 
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \ 
            -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/wazuh/wazuh-agent-packages/actions/workflows/packages-upload-image-amd.yml/dispatches \  
            -d '{"ref": "${{ env.WAZUH_WORKFLOWS_BRANCH }}", \
            "inputs": {"container_name": "pkg_rpm_agent_builder_i386", \ 
                       "dockerfile_path": "packages/rpms/i386/agent", \
                       "tag": "${{ env.TAG }}", \  
                       "wazuh_wazuh_branch": "${{ github.ref_name }}"}}'

      - name: Request pkg_rpm_legacy_builder_amd64 update
        if: steps.changes.outputs.pkg_rpm_legacy_builder_amd64 == 'true'
        run: | 
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \ 
            -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/wazuh/wazuh-agent-packages/actions/workflows/packages-upload-image-amd.yml/dispatches \  
            -d '{"ref": "${{ env.WAZUH_WORKFLOWS_BRANCH }}", \
            "inputs": {"container_name": "pkg_rpm_legacy_builder_amd64", \ 
                       "dockerfile_path": "packages/rpms/amd64/legacy", \
                       "tag": "${{ env.TAG }}", \  
                       "wazuh_wazuh_branch": "${{ github.ref_name }}"}}'

      - name: Request pkg_rpm_legacy_builder_i386 update
        if: steps.changes.outputs.pkg_rpm_legacy_builder_i386 == 'true'
        run: | 
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \ 
            -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/wazuh/wazuh-agent-packages/actions/workflows/packages-upload-image-amd.yml/dispatches \  
            -d '{"ref": "${{ env.WAZUH_WORKFLOWS_BRANCH }}", \
            "inputs": {"container_name": "pkg_rpm_legacy_builder_i386", \ 
                       "dockerfile_path": "packages/debs/i386/legacy", \
                       "tag": "${{ env.TAG }}", \  
                       "wazuh_wazuh_branch": "${{ github.ref_name }}"}}'

      - name: Request compile_windows_agent update
        if: steps.changes.outputs.compile_windows_agent == 'true'
        run: | 
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \ 
            -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/wazuh/wazuh-agent-packages/actions/workflows/packages-upload-image-amd.yml/dispatches \  
            -d '{"ref": "${{ env.WAZUH_WORKFLOWS_BRANCH }}", \
            "inputs": {"container_name": "compile_windows_agent", \ 
                       "dockerfile_path": "packages/windows", \
                       "tag": "${{ env.TAG }}", \  
                       "wazuh_wazuh_branch": "${{ github.ref_name }}"}}'
