name: Build multiple Wazuh Manager Packages - DEB|RPM - amd64|arm64
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Wazuh branch used while building a package'
        required: false
        default: master
      build-amd64-deb:
        type: choice
        description: 'Build .deb wazuh-manager on amd64 arch'
        required: true
        options: 
          - 'yes'
          - 'no'
      build-amd64-rpm:
        type: choice
        description: 'Build .rpm wazuh-manager on amd64 arch'
        required: true
        options: 
          - 'yes'
          - 'no'
      build-arm64-deb:
        type: choice
        description: 'Build .deb wazuh-manager on arm64 arch'
        required: true
        options: 
          - 'yes'
          - 'no'
      build-arm64-rpm:
        type: choice
        description: 'Build .rpm wazuh-manager on arm64 arch'
        required: true
        options: 
          - 'yes'
          - 'no'
      revision:
        type: string
        description: |
          'Set the value to "1" for packages in release format.
          You can also add other values, such as issue numbers.
          By default, it is set to "0" for development.'
        required: false
      release-package:
        type: choice
        description: |
          'Build packages with release format.
           Checksum will be also generated.'
        required: false
        options: 
          - 'yes'
          - 'no'
      debuggable-package:
        type: string
        description: 'Build packages with debug symbols.'
        default: 'no'
        required: false

jobs:
   Build-manager-amd64-deb: 
    if: ${{ inputs.build-amd64-deb == 'yes' }}
    uses: ./.github/workflows/packages-build-manager.yml
    with:
        branch: ${{ inputs.branch }}
        arch: amd64
        package-format: deb
        revision: ${{ inputs.revision}}
        release-package: ${{ inputs.release-package }}
        debuggable-package: ${{ inputs.debuggable-package }}
        runner-machine: ubuntu-latest
    secrets: inherit

   Build-manager-amd64-rpm: 
    if: ${{ inputs.build-amd64-rpm == 'yes' }}
    uses: ./.github/workflows/packages-build-manager.yml
    with:
        branch: ${{ inputs.branch }}
        arch: amd64
        package-format: rpm
        revision: ${{ inputs.revision}}
        release-package: ${{ inputs.release-package }}
        debuggable-package: ${{ inputs.debuggable-package }}
        runner-machine: ubuntu-latest
    secrets: inherit
    
   Build-manager-arm64-deb: 
    if: ${{ inputs.build-arm64-deb == 'yes' }}
    uses: ./.github/workflows/packages-build-manager.yml
    with:
        branch: ${{ inputs.branch }}
        arch: arm64
        package-format: deb
        revision: ${{ inputs.revision}}
        release-package: ${{ inputs.release-package }}
        debuggable-package: ${{ inputs.debuggable-package }}
        runner-machine: self-hosted-arm
    secrets: inherit

   Build-manager-arm64-rpm: 
    if: ${{ inputs.build-arm64-rpm == 'yes' }}
    uses: ./.github/workflows/packages-build-manager.yml
    with:
        branch: ${{ inputs.branch }}
        arch: arm64
        package-format: rpm
        revision: ${{ inputs.revision}}
        release-package: ${{ inputs.release-package }}
        debuggable-package: ${{ inputs.debuggable-package }}
        runner-machine: self-hosted-arm
    secrets: inherit
