name: Package - Upload Docker images for linux agent - DEB|RPM - amd64 and i386
on:
  workflow_dispatch:
    inputs:
      tag:
        description: |
          Tag name of the Docker image to be uploaded.
          Use 'developer' to set branch name as tag.
          Use 'auto' to set branch version as tag.
          Default is 'auto'.
      arch:
        type: choice
        description: 'Build .deb wazuh-agent on arm64 arch'
        required: true
        options:
          - 'amd64'
          - 'i386'
      package-format:
        type: choice
        description: 'Package format [deb, rpm]'
        required: true
        options:
          - deb
          - rpm
      legacy:
        type: boolean
        description: |
          'Only for RPM - Build package for CentOS 5.'
        required: false

jobs:
  Upload-package-building-images:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - uses: actions/checkout@v4

      - name: Set-env
        run: |
          if [ "${{ inputs.legacy }}" == "true" ]; then
            echo "CONTAINER_NAME=pkg_${{ inputs.package-format }}_legacy_builder_${{ inputs.arch}}" >> $GITHUB_ENV
            echo "DOCKERFILE_PATH=packages/${{ inputs.package-format }}s/${{ inputs.arch}}/legacy" >> $GITHUB_ENV
          else
            echo "CONTAINER_NAME=pkg_${{ inputs.package-format }}_agent_builder_${{ inputs.arch}}" >> $GITHUB_ENV
            echo "DOCKERFILE_PATH=packages/${{ inputs.package-format }}s/${{ inputs.arch}}/agent" >> $GITHUB_ENV
          fi

      - name: Copy build.sh and utils to Dockerfile path
        run: |
          cp $GITHUB_WORKSPACE/packages/build.sh $GITHUB_WORKSPACE/${{ env.DOCKERFILE_PATH }}
          cp $GITHUB_WORKSPACE/packages/${{ inputs.package-format }}s/utils/* $GITHUB_WORKSPACE/${{ env.DOCKERFILE_PATH }}

      - name: Copy centos-5-i386.tar.gz to Dockerfile legacy path
        if: inputs.legacy == 'true' || inputs.legacy == true
        run: |
          cd $GITHUB_WORKSPACE/${{ env.DOCKERFILE_PATH }}
          curl -sO "https://packages-dev.wazuh.com/utils/centos-5-i386-build/centos-5-i386.tar.gz"

      - name: Set tag
        run: |
          VERSION=$(sed 's/.*\([0-9]\.[0-9]*\.[0-9]*\).*/\1/' $GITHUB_WORKSPACE/src/VERSION)
          if [ "${{ inputs.tag }}" == "auto" ]; then echo "TAG=$VERSION" >> $GITHUB_ENV;
          elif [ "${{ inputs.tag }}" == "developer" ]; then echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV;
          else echo "TAG=${{ inputs.tag }}" >> $GITHUB_ENV; fi

      - name: Build and push image ${{ env.CONTAINER_NAME }} with tag ${{ env.TAG }} to Github Container Registry
        run: |
          bash $GITHUB_WORKSPACE/.github/actions/ghcr-pull-and-push/build_and_push_image_to_ghcr.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.actor}} ${{env.CONTAINER_NAME}} ${{ env.DOCKERFILE_PATH }} ${{ env.TAG }}
