name: Build Wazuh Agent Packages - Windows
on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: |
          Tag name of the Docker image to be downloaded.
          Use 'developer' to set branch name as tag.
          Use 'auto' to set branch version as tag.
          Default is 'auto'.
        required: false
        default: 'auto'
      revision:
        description: |
          Revision used to naming Windows package.
          Default is '0'.
        required: false
        default: '0'
      is_stage:
        type: boolean
        description: Should set development/production nomenclature. By default 'development'.
        required: false
      debug:
        type: boolean
        description: Activate debug mode in the compilation. By Default is 'false'.
        required: false
      trust_verification:
        type: choice
        description: |
          This flag controls the dll and exe files signature verification mechanism.
          Use '0' to disable mechanism.
          Use '1' to warning only.
          Use '2' to full enforce.
          Default is '1'.
        options:
          - 0
          - 1
          - 2
        required: false
        default: '1'
      ca_name:
        description: |
          CA name to be used to verify the trust of the agent."
          Default is 'DigiCert Assured ID Root CA'.
        required: false
        default: 'DigiCert Assured ID Root CA'
      checksum:
        type: boolean
        description: Generate checksum on the same directory than the package.
        required: false

jobs:
  build-agent-windows-base:
    runs-on: ubuntu-latest
    outputs:
      zip_s3_url: ${{ steps.push_zip.outputs.s3_base_agent }}
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - uses: actions/checkout@v4

      - name: Set VERSION and CONTAINER_NAME
        run: |
          echo "VERSION=$(sed 's/.*\([0-9]\.[0-9]*\.[0-9]*\).*/\1/' $GITHUB_WORKSPACE/src/VERSION)" >> $GITHUB_ENV
          echo "CONTAINER_NAME=compile_windows_agent" >> $GITHUB_ENV

      - name: Set TAG
        run: |
          if [ "${{ inputs.docker_image_tag }}" == "auto" ]; then echo "TAG=${{ env.VERSION }}" >> $GITHUB_ENV;
          elif [ "${{ inputs.docker_image_tag }}" == "developer" ]; then echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV;
          else echo "TAG=${{ inputs.docker_image_tag }}" >> $GITHUB_ENV; fi

      - name: Set ZIP_NAME
        run: |
          COMMIT_HASH="$(git rev-parse --short HEAD)"
          if [ "${{ inputs.naming_format }}" == "release" ]; then
            echo "ZIP_NAME=wazuh-agent-${{ env.VERSION }}-${{ inputs.revision }}.zip" >> $GITHUB_ENV;
          else
            echo "ZIP_NAME=wazuh-agent_${{ env.VERSION }}-${{ inputs.revision }}_windows_${COMMIT_HASH}.zip" >> $GITHUB_ENV;
          fi

      - name: Download docker image for package building
        run: |
          bash $GITHUB_WORKSPACE/.github/actions/ghcr-pull-and-push/pull_image_from_ghcr.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.actor}} $CONTAINER_NAME ${{ env.TAG }}

      - name: Build Windows wazuh-agent
        working-directory: packages/windows
        run: |
          FLAGS="-s /tmp --dont-build-docker -j $(nproc) -o ${{ env.ZIP_NAME }} "
          if [ "${{ inputs.debug}}" == "true" ]; then FLAGS+="--debug "; fi
          bash generate_compiled_windows_agent.sh -t ${{ inputs.trust_verification }} --tag ${{ env.TAG }} -c "${{ inputs.ca_name }}" $FLAGS

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_SECRET_KEY }}
          aws-region: us-east-1

      - name: Upload package to S3
        id: push_zip
        run: |
          s3_packages_url="s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages"
          if [ inputs.checksum == 'true'  ]; then
            sha512sum "/tmp/${{ env.ZIP_NAME }}" > "/tmp/${{ env.ZIP_NAME }}.sha512"
            aws s3 cp /tmp/${{ env.ZIP_NAME }}.sha512 "${s3_packages_url}/"
          fi
          aws s3 cp /tmp/${{ env.ZIP_NAME }} "${s3_packages_url}/"
          echo "s3_base_agent=${s3_packages_url}/${{ env.ZIP_NAME }}" >> "$GITHUB_OUTPUT"

  generate-msi-agent:
    runs-on: windows-latest
    needs: build-agent-windows-base
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".github/workflows/.python-version"
          architecture: x64
      - name: Add WiX toolkit to PATH
        shell: bash
        run: echo "${WIX}bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          pip install -r src/win32/qa/requirements.txt

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_SECRET_KEY }}
          aws-region: us-east-1

      - name: Download windows agent base from S3
        run: |
          mkdir C:\win-agent-base\
          aws s3 cp ${{ needs.build-agent-windows-base.outputs.zip_s3_url }} C:\win-agent-base\win-agent-base.zip
          # $s3_packages_url = "s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages"
          # aws s3 cp ${s3_packages_url}/wazuh-agent_4.9.0-0_windows_fff8611.zip  C:\win-agent-base\win-agent-base.zip

      - name: Unzip base folder
        run: |
          7z x C:\win-agent-base\win-agent-base.zip -oC:\win-agent-base

      - name: Create .msi package
        run: |
          cd C:\win-agent-base\wazuh-local-src\src\win32
          $VERSION = Get-Content ..\VERSION
          .\wazuh-installer-build-msi.bat $VERSION 0
          cp *.msi C:\win-agent-base\

      - name: Upload msi to s3
        run: |
          $s3_packages_url = "s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages"
          $msi_files = Get-ChildItem C:\win-agent-base\*.msi
          foreach ($msi in $msi_files) {
            aws s3 cp $msi.FullName "$s3_packages_url/"
          }
