name: Build macOS Wazuh Agent Packages - intel64|arm64
on:
  workflow_dispatch:
    inputs:
      architecture:
        type: choice
        description: Package architecture [intel64, arm64].
        options:
          - intel64
          - arm64
        required: true
        default: 'intel64'
      revision:
        description: |
          Package revision (name and metadata).
          Default is '0'.
        required: false
        default: "0"
      is_stage:
        type: boolean
        description: |
          Should set development/production nomenclature
          True if package name should have production format.
          False if package name should have developer format.
          Default is 'false'.
        required: false
      debug:
        type: boolean
        description: |
          Activate debug mode in the compilation.
          Default is 'false'.
        required: false
      checksum:
        type: boolean
        description: Generate checksum on the same directory than the package.
        required: false

  workflow_call:
    inputs:
      architecture:
        type: string
        required: true
      revision:
        type: string
        required: false
      is_stage:
        type: boolean
        required: false
      debug:
        type: boolean
        required: false
      checksum:
        type: boolean
        required: false

jobs:
  build-agent-macos-packages:
    runs-on: macos-latest
    name: Build macOS wazuh-agent on ${{ inputs.architecture }}

    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - uses: actions/checkout@v4

      - name: Compile Wazuh agent and generate package
        working-directory: packages/macos/
        run: |
          nproc=$(sysctl -n hw.ncpu)
          FLAGS="-j $nproc -r ${{ inputs.revision }} "
          if [ "${{ inputs.is_stage }}" == "true" ]; then FLAGS+="--is_stage "; fi
          if [ "${{ inputs.checksum }}" == "true" ]; then FLAGS+="--checksum "; fi
          if [ "${{ inputs.debug}}" == "true" ]; then FLAGS+="--debug "; fi
          bash generate_wazuh_packages.sh -i
          echo "generate_wazuh_packages.sh -a ${{ inputs.architecture }} $FLAGS"
          sudo bash generate_wazuh_packages.sh -a ${{ inputs.architecture }} $FLAGS

      - name: Test install Wazuh agent
        working-directory: packages/macos/output
        run: |
          sudo echo "WAZUH_MANAGER='1.1.1.1'" > /tmp/wazuh_envs && sudo installer -pkg *agent*pkg -target / | sudo tee ./installer.log
          if grep -q "The install was successful" "./installer.log"; then
            echo "Installation successfully."
          else
            echo "The installation could not be completed. The package will not be uploaded.";
            exit 1;
          fi

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_SECRET_KEY }}
          aws-region: us-east-1

      - name: Upload package and checksum to S3
        working-directory: packages/macos/
        run: |
          for file in output/*agent*; do
            aws s3 cp $file s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages/
          done
