name: Running RTR for all targets

on:
  pull_request:
    paths:
      - "src/**"

jobs:
  ready_to_review:
    strategy:
          matrix:
              module: [wazuh_modules/syscollector, shared_modules/dbsync, shared_modules/rsync, shared_modules/utils, data_provider, syscheckd]
              target: [agent, winagent]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install mingw
        if: matrix.target == 'winagent'
        run: sudo apt install gcc-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 nsis -y
      - name: Install dependencies
        run: sudo apt install cppcheck astyle valgrind clang-tools -y
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".github/workflows/.python-version"
          architecture: x64
      - name: Run RTR for module ${{ matrix.module }} and target ${{ matrix.target }}
        run:
          cd src/
          python build.py --target ${{ matrix.target }} --readytoreview ${{ matrix.module }}
  scan_build:
    strategy:
          matrix:
            target: [agent, server, winagent]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install mingw
        if: matrix.target == 'winagent'
        run: sudo apt install gcc-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 nsis -y
      - name: Install dependencies
        run: sudo apt install clang-tools -y
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".github/workflows/.python-version"
          architecture: x64
      - name: Run scan-build for target ${{ matrix.target }}
        run:
          cd src/
          python build.py --scanbuild ${{ matrix.target }}
