name: Scan build
on: push

jobs:
    scan-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y clang-tools-14
            - name: Build
              run: |
                  cd src
                  make deps TARGET=agent -j2
                  scan-build --status-bugs --force-analyze-debug-code -o scan-build-report --exclude external/ make TARGET=agent DEBUG=1 -j2
            - name: Upload scan-build report
              uses: actions/upload-artifact@v2
              with:
                  name: scan-build-report
                  path: src/scan-build-report
