name: Vulnerability Scanner

on:
  pull_request:
    # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
    # Path filtering
    paths:
      - ".github/workflows/vulnerability-scanner-tests.yml"
      - "src/shared_modules/router/**"
      - "src/shared_modules/content_manager/**"
      - "src/shared_modules/indexer_connector/**"
      - "src/wazuh_modules/vulnerability_scanner/**"
      - "src/wazuh_modules/http-request/**"

jobs:
  style-and-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0 # We need to fetch all the history to calculate the deltas.

      # Check which modules have been modified.
      # Could be used to avoid some steps if possible (Doxygen, Style, etc.)
      - name: Calculate deltas
        run: |

          DIFFS=$(git diff --name-only origin/${{ github.head_ref }} origin/${{ github.base_ref }})

          if echo $DIFFS | grep 'src/shared_modules/router/'; then
            echo "ROUTER=true" >> "$GITHUB_ENV"
          else
            echo "ROUTER=false" >> "$GITHUB_ENV"
          fi

          if echo $DIFFS | grep 'src/shared_modules/content_manager/'; then
            echo "CONTENT_MANAGER=true" >> "$GITHUB_ENV"
          else
            echo "CONTENT_MANAGER=false" >> "$GITHUB_ENV"
          fi

          if echo $DIFFS | grep 'src/shared_modules/indexer_connector/'; then
            echo "INDEXER_CONNECTOR=true" >> "$GITHUB_ENV"
          else
            echo "INDEXER_CONNECTOR=false" >> "$GITHUB_ENV"
          fi

          if echo $DIFFS | grep 'src/wazuh_modules/vulnerability_scanner/'; then
            echo "VULNERABILITY_SCANNER=true" >> "$GITHUB_ENV"
          else
            echo "VULNERABILITY_SCANNER=false" >> "$GITHUB_ENV"
          fi

      # Router
      - name: Router - Codding style
        if: env.ROUTER == 'true'
        uses: ./.github/actions/clang_format
        with:
          path: src/shared_modules/router

      - name: Router - Doxygen
        if: env.ROUTER == 'true'
        uses: ./.github/actions/doxygen
        with:
          path: src/shared_modules/router

      # Indexer connector
      - name: Indexer connector - Codding style
        if: env.INDEXER_CONNECTOR == 'true'
        uses: ./.github/actions/clang_format
        with:
          path: src/shared_modules/indexer_connector

      - name: Indexer connector - Doxygen
        if: env.INDEXER_CONNECTOR == 'true'
        uses: ./.github/actions/doxygen
        with:
          path: src/shared_modules/indexer_connector

      # Content manager
      - name: Content manager - Codding style
        if: env.CONTENT_MANAGER == 'true'
        uses: ./.github/actions/clang_format
        with:
          path: src/shared_modules/content_manager

      - name: Content manager - Doxygen
        if: env.CONTENT_MANAGER == 'true'
        uses: ./.github/actions/doxygen
        with:
          path: src/shared_modules/content_manager

      # Vulnerability scanner
      - name: Vulnerability scanner - Codding style
        if: env.VULNERABILITY_SCANNER == 'true'
        uses: ./.github/actions/clang_format
        with:
          path: src/wazuh_modules/vulnerability_scanner

      - name: Vulnerability scanner - Doxygen
        if: env.VULNERABILITY_SCANNER == 'true'
        uses: ./.github/actions/doxygen
        with:
          path: src/wazuh_modules/vulnerability_scanner

  vulnerability-scanner-modules:
    needs: style-and-documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Project dependencies
        run: |
          cd src
          make deps TARGET=server -j2
          make build_gtest TARGET=server -j2
          make libwazuhext.so TARGET=server -j2
          SRC_FOLDER=$(pwd)
          cd shared_modules/http-request
          mkdir -p build && cd build && cmake .. -DCMAKE_PROJECT_NAME=http-request -DSRC_FOLDER=${SRC_FOLDER} && make

      ########################
      # Compilation and test #
      ########################

      # Router
      - name: Router - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/router

      - name: Router - Coverage
        uses: ./.github/actions/coverage
        with:
          path: src/shared_modules/router

      # Indexer connector
      - name: Indexer connector - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/indexer_connector

      - name: Indexer connector - Coverage
        uses: ./.github/actions/coverage
        with:
          path: src/shared_modules/indexer_connector

      # Content manager
      - name: Content manager - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/content_manager

      - name: Content manager - Coverage
        uses: ./.github/actions/coverage
        with:
          path: src/shared_modules/content_manager

      # Vulnerability scanner
      - name: Vulnerability scanner - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/vulnerability_scanner

      - name: Vulnerability scanner - Coverage
        uses: ./.github/actions/coverage
        with:
          path: src/wazuh_modules/vulnerability_scanner

  vulnerability-scanner-modules-asan:
    needs: style-and-documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Project dependencies
        run: |
          cd src
          make deps TARGET=server -j2
          make build_gtest TARGET=server -j2

          cd external
          git clone https://github.com/yhirose/cpp-httplib.git
          cd ..

      ########################
      # Compilation and test #
      ########################

      ### ASAN testing ###
      # Router
      - name: Router
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/router
          asan: "true"

      # indexer connector
      - name: Indexer connector
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/content_manager
          asan: "true"

      # content manager
      - name: Content manager
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/indexer_connector
          asan: "true"

      # Vulnerability scanner
      - name: Vulnerability scanner
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/vulnerability_scanner
          asan: "true"

      ### Valgrind testing ###
      # Router
      - name: Router
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/router

      # indexer connector
      - name: Indexer connector
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/content_manager

      # content manager
      - name: Content manager
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/indexer_connector

      # Vulnerability scanner
      - name: Vulnerability scanner
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/vulnerability_scanner
