name: Vulnerability Scanner

on:
  pull_request:
    # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]

    # Path filtering
    paths:
      - ".github/workflows/vulnerability-scanner-tests.yml"
      - "src/shared_modules/router/**"
      - "src/shared_modules/content_manager/**"
      - "src/shared_modules/indexer_connector/**"
      - "src/wazuh_modules/vulnerability_scanner/**"
      - "src/wazuh_modules/wazuh-http-request/**"

jobs:
  style-and-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      # Router
      - name: Router - Format
        uses: ./.github/actions/clang_format
        with:
          path: src/shared_modules/router         

      # Indexer connector
      - name: Indexer connector - Format
        uses: ./.github/actions/clang_format
        with:
          path: src/shared_modules/indexer_connector       

      # Content manager
      - name: Content manager - Format
        uses: ./.github/actions/clang_format
        with:
          path: src/shared_modules/content_manager            

      # Vulnerability scanner
      - name: Vulnerability scanner - Format
        uses: ./.github/actions/clang_format
        with:
          path: src/wazuh_modules/vulnerability_scanner


  vulnerability-scanner-modules:
    needs: style-and-documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Project dependencies
        run: |
          cd src
          make deps TARGET=server -j2
          make build_gtest TARGET=server -j2
          make libwazuhext.so TARGET=server -j2
          SRC_FOLDER=$(pwd)
          cd shared_modules/http-request
          mkdir -p build && cd build && cmake .. -DCMAKE_PROJECT_NAME=http-request -DSRC_FOLDER=${SRC_FOLDER} && make

      ########################
      # Compilation and test #
      ########################

      # Router
      - name: Router - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/router

      - name: Router - Coverage
        uses: ./.github/actions/coverage
        with:
          path: src/shared_modules/router          

      # Indexer connector
      - name: Indexer connector - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/indexer_connector

      - name: Indexer connector - Coverage
        uses: ./.github/actions/coverage
        with:
          path: src/shared_modules/indexer_connector            

      # Content manager
      - name: Content manager - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/content_manager

      - name: Content manager - Coverage
        uses: ./.github/actions/coverage
        with:
          path: src/shared_modules/content_manager            

      # Vulnerability scanner
      - name: Vulnerability scanner - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/vulnerability_scanner

      - name: Vulnerability scanner - Coverage
        uses: ./.github/actions/coverage
        with:
          path: src/wazuh_modules/vulnerability_scanner              

  vulnerability-scanner-modules-asan:
    needs: style-and-documentation    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Project dependencies
        run: |
          cd src
          make deps TARGET=server -j2
          make build_gtest TARGET=server -j2

          cd external
          git clone https://github.com/yhirose/cpp-httplib.git
          cd ..

          cd shared_modules/wazuh-http-request
          mkdir -p build && cd build && cmake .. && make

      ########################
      # Compilation and test #
      ########################

      ### ASAN testing ###
      # Router
      - name: Router
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/router
          asan: "true"

      # indexer connector
      - name: Indexer connector
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/content_manager
          asan: "true"

      # content manager
      - name: Content manager
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/indexer_connector
          asan: "true"

      # Vulnerability scanner
      - name: Vulnerability scanner
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/vulnerability_scanner
          asan: "true"

      ### Valgrind testing ###
      # Router
      - name: Router
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/router

      # indexer connector
      - name: Indexer connector
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/content_manager

      # content manager
      - name: Content manager
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/indexer_connector

      # Vulnerability scanner
      - name: Vulnerability scanner
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/vulnerability_scanner
