name: Vulnerability Scanner

on:
  push:
    paths:
      - ".github/workflows/vulnerability-scanner-tests.yml"
      - "src/shared_modules/router/**"
      - "src/shared_modules/content_manager/**"
      - "src/shared_modules/indexer_connector/**"
      - "src/wazuh_modules/vulnerability_scanner/**"
      - "src/wazuh_modules/wazuh-http-request/**"

jobs:
  vulnerability-scanner-modules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 2 # We need to fetch 2 commits to get the diff.

      # For this scenario ([see dependencies matrix](https://github.com/wazuh/wazuh/issues/17952#issuecomment-1645614459)) 
      # we need to compile all the modules. This step is usefull for scenario where we can avoid the compilation of some steps
      # - name: Check for compilation requirement
      #   run: |
      #     DIFFS=$(git diff --name-only HEAD HEAD~1)

      #     if echo $DIFFS | grep 'src/shared_modules/router/'; then
      #       echo "ROUTER=true" >> "$GITHUB_ENV"
      #     else
      #       echo "ROUTER=false" >> "$GITHUB_ENV"
      #     fi

      #     if echo $DIFFS | grep 'src/shared_modules/content_manager/'; then
      #       echo "CONTENT_MANAGER=true" >> "$GITHUB_ENV"
      #     else
      #       echo "CONTENT_MANAGER=false" >> "$GITHUB_ENV"
      #     fi

      #     if echo $DIFFS | grep 'src/shared_modules/indexer_connector/'; then
      #       echo "INDEXER_CONNECTOR=true" >> "$GITHUB_ENV"
      #     else
      #       echo "INDEXER_CONNECTOR=false" >> "$GITHUB_ENV"
      #     fi

      #     if echo $DIFFS | grep 'src/wazuh_modules/vulnerability_scanner/'; then
      #       echo "VULNERABILITY_SCANNER=true" >> "$GITHUB_ENV"
      #     else
      #       echo "VULNERABILITY_SCANNER=false" >> "$GITHUB_ENV"
      #     fi

      - name: Prepare dependencies
        run: |
          cd src
          make deps TARGET=server -j2
          make build_gtest TARGET=server -j2

          cd external
          git clone https://github.com/yhirose/cpp-httplib.git
          cd ..

          cd shared_modules/wazuh-http-request
          mkdir -p build && cd build && cmake .. && make

      # All modules depend of the router. We compile it first
      - name: Build router
        run: |
          cd src/shared_modules/router
          mkdir -p build && cd build && cmake .. && make -j2
          ctest

      # Vulnerability scanner depends of the indexer_connector and content_manager
      - name: Build indexer_connector and content_manager
        run: |
          cd src/shared_modules
          
          # Compile the 
          cd indexer_connector
          mkdir -p build && cd build && cmake .. && make -j2
          ctest
          cd ../..

          cd content_manager
          mkdir -p build && cd build && cmake .. && make -j2
          ctest
          cd ../..
          
          # Wait for the compilation to finish
          wait

      # Vulnerability scanner depends of all the modules. We compile it last
      - name: Build vulnerability_scanner
        run: |
          cd src/wazuh_modules/vulnerability_scanner
          mkdir -p build && cd build && cmake .. && make -j2
          ctest

# TODO add testing workflow
