name: wazuh-template for Elasticsearch test

# if the file wazuh/extensions/elasticsearch/7.x/wazuh-template.json is modified launch the test or is a part of
# a pull request

on:
  push:
    paths:
      - "extensions/elasticsearch/7.x/**"
      - ".github/workflows/wazuh-template-elasticsearch.yml"

jobs:
  wazuh-template-elasticsearch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: ./.github/actions/setup-python
        with:
          python-version-file: ".github/workflows/.python-version"
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r extensions/elasticsearch/7.x/qa/requirements.txt
      - name: Test wazuh-template for Elasticsearch
        run: |
          cd extensions/elasticsearch/7.x
          python -m pytest -vv qa/
