name: Syscollector test on Windows

on:
  pull_request:
    paths:
      - ".github/workflows/windows-syscollector-tests.yml"
      - "src/data_provider/**"
      - "src/shared_modules/**"
      - "src/wazuh_modules/syscollector/**"
      - "src/Makefile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install mingw
        run: sudo apt install gcc-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 nsis -y
      - name: make deps
        run: make -C src deps TARGET=winagent -j2
      - name: make
        run: make -C src TARGET=winagent -j2
        # Make folder and upload as artifacts.
      - name: Copy libraries
        run: |
          mkdir -p src/shared_libraries
          cp src/libwazuhext.dll src/shared_libraries/
          cp src/win32/libgcc_s_dw2-1.dll src/shared_libraries/
          cp src/win32/libstdc++-6.dll src/shared_libraries/
          cp src/win32/libwinpthread-1.dll src/shared_libraries/
      # Upload build artifacts for the shared libraries.
      - name: Upload Artifact shared_libraries
        uses: ./.github/actions/upload-artifact
        with:
          name: shared_libraries
          path: src/shared_libraries
      # Upload build artifacts for the data provider.
      - name: Upload Artifact data_provider
        uses: ./.github/actions/upload-artifact
        with:
          name: data_provider
          path: src/data_provider/build/bin
      # Upload build artifacts for dbsync.
      - name: Upload Artifact dbsync
        uses: ./.github/actions/upload-artifact
        with:
          name: dbsync
          path: src/shared_modules/dbsync/build/bin
      # Upload build artifacts for rsync.
      - name: Upload Artifact rsync
        uses: ./.github/actions/upload-artifact
        with:
          name: rsync
          path: src/shared_modules/rsync/build/bin
      # Upload build artifacts for syscollector.
      - name: Upload Artifact syscollector
        uses: ./.github/actions/upload-artifact
        with:
          name: syscollector
          path: src/wazuh_modules/syscollector/build/bin
  run-on-windows:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: ./.github/actions/setup-python
        with:
          python-version-file: ".github/workflows/.python-version"
          architecture: x64
      - name: Download Artifact data_provider
        uses: ./.github/actions/download-artifact
        with:
          name: data_provider
          path: C:\data_provider\
      - name: Download Artifact dbsync
        uses: ./.github/actions/download-artifact
        with:
          name: dbsync
          path: C:\dbsync\
      - name: Download Artifact rsync
        uses: ./.github/actions/download-artifact
        with:
          name: rsync
          path: C:\rsync\
      - name: Download Artifact syscollector
        uses: ./.github/actions/download-artifact
        with:
          name: syscollector
          path: C:\syscollector\
      - name: Download Artifact shared_libraries
        uses: ./.github/actions/download-artifact
        with:
          name: shared_libraries
          path: C:\shared_libraries\
      # Copy dbsync, rsync and sysinfo libraries into syscollector.
      - name: Copy libraries into syscollector (dbsync, rsync and sysinfo)
        run: |
          copy C:\dbsync\*.dll C:\syscollector\
          copy C:\rsync\*.dll C:\syscollector\
          copy C:\data_provider\*.dll C:\syscollector\
      # Copy dbsync library into rsync.
      - name: Copy libraries into rsync (dbsync)
        run: |
          copy C:\dbsync\*.dll C:\rsync\
      - name: Copy shared libraries
        run: |
          copy C:\shared_libraries\* C:\data_provider\
          copy C:\shared_libraries\* C:\dbsync\
          copy C:\shared_libraries\* C:\rsync\
          copy C:\shared_libraries\* C:\syscollector\
      - name: Install dependencies
        run: |
          pip install -r src/data_provider/qa/requirements.txt
      - name: Run tests
        run: |
          cd src/data_provider
          python -m pytest -vv qa/
